name: credrails

services:
  db:
    image: postgres:14
    container_name: postgres-db-prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env.prod

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api-prod
    command: gunicorn --bind 0.0.0.0:8000 myproject.wsgi:application
    env_file:
      - ./backend/.env.prod
    environment:
      - DEBUG=0
    expose:
      - '8000'
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx-prod
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '80:80'
    links:
      - backend

  # we could set up a redis service here
  # redis:
  #   image: redis
  #   container_name: redis

  # we could set up a react/vue/svelte service here
  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: frontend

volumes:
  postgres_data_prod:
